In [13]:
#image with 10000 fram diffreant color auto

import cv2
import numpy as np 
from matplotlib import pyplot as plt 
from random import randint
cv2.namedWindow('image')

img=np.zeros((500,500,3),np.uint8)
#cv2.namedWindow('image')
i=0
j=0
k=0
imgs_list=[]
size = (500,500)
for i in range(200):
    r = randint(0, 255)
    g = randint(0, 255)
    b = randint(0, 255)
    img[:,:]=[r,g,b]
    print(img)
    imgs_list.append(img)
    cv2.imshow("image",img)
    k=cv2.waitKey(1)
    if k == ord('q'):
        break
cv2.destroyAllWindows()    

for j in range(len(imgs_list)): 
    print(imgs_list[j])

out = cv2.VideoWriter('project.avi',cv2.VideoWriter_fourcc(*'DIVX'), 15, size)

for k in range(len(imgs_list)):
    #print(imgs_list[i])
    out.write(imgs_list[k])
out.release()


[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 ...

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]]
[[[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 ...

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 [[ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]
  ...
  [ 75   3 172]
  [ 75   3 172]
  [ 75   3 172]]

 [[ 